### ISSUE TITLE
Add error to TextField's and TextArea's onChange callback

### ISSUE THREAD

**Issue by elvisvoer** [airtame/airtame-gooey-react#13]
Hey @mmellado @agjs 

The TextField and TextArea components have both a `maxContentLength` prop which if it is exceeded an error message is being displayed. I think we should pass an error to the  `onChange` callback. Something like:

`this.props.onChange(event, error)`

What do you guys think?

**Comment by elvisvoer** [comment]
Actually, I just checked and the Select component sends the `event` and the `id` of the selected option so in order to keep the API consistent maybe we should do change the `onChange` for the select to be 

`this.props.OnChange(event, error, id)`

**Comment by mmellado** [comment]
This is a very good idea :)
